//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub mod prelude;

pub mod accounts;
pub mod accounts_followers;
pub mod favourites;
pub mod jobs;
pub mod media_attachments;
pub mod oauth2_access_tokens;
pub mod oauth2_applications;
pub mod oauth2_authorization_codes;
pub mod oauth2_refresh_tokens;
pub mod posts;
pub mod posts_media_attachments;
pub mod posts_mentions;
pub mod users;
pub mod users_roles;
