//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

pub use super::accounts::Entity as Accounts;
pub use super::accounts_followers::Entity as AccountsFollowers;
pub use super::favourites::Entity as Favourites;
pub use super::jobs::Entity as Jobs;
pub use super::media_attachments::Entity as MediaAttachments;
pub use super::oauth2_access_tokens::Entity as Oauth2AccessTokens;
pub use super::oauth2_applications::Entity as Oauth2Applications;
pub use super::oauth2_authorization_codes::Entity as Oauth2AuthorizationCodes;
pub use super::oauth2_refresh_tokens::Entity as Oauth2RefreshTokens;
pub use super::posts::Entity as Posts;
pub use super::posts_mentions::Entity as PostsMentions;
pub use super::reposts::Entity as Reposts;
pub use super::users::Entity as Users;
pub use super::users_roles::Entity as UsersRoles;
