query LoadPost($id: UUID!) {
	getPostById(id: $id) {
		id
		account {
			id
			displayName
			username
		}
		subject
		content
		attachments {
			contentType
			description
			url
		}
		visibility
		url
		createdAt
	}
}
