use isolang::Language;

#[cfg(feature = "whatlang")]
pub fn whatlang_to_isolang(lang: whatlang::Lang) -> Language {
    match lang {
        whatlang::Lang::Epo => Language::Epo,
        whatlang::Lang::Eng => Language::Eng,
        whatlang::Lang::Rus => Language::Rus,
        whatlang::Lang::Cmn => Language::Cmn,
        whatlang::Lang::Spa => Language::Spa,
        whatlang::Lang::Por => Language::Por,
        whatlang::Lang::Ita => Language::Ita,
        whatlang::Lang::Ben => Language::Ben,
        whatlang::Lang::Fra => Language::Fra,
        whatlang::Lang::Deu => Language::Deu,
        whatlang::Lang::Ukr => Language::Ukr,
        whatlang::Lang::Kat => Language::Kat,
        whatlang::Lang::Ara => Language::Ara,
        whatlang::Lang::Hin => Language::Hin,
        whatlang::Lang::Jpn => Language::Jpn,
        whatlang::Lang::Heb => Language::Heb,
        whatlang::Lang::Yid => Language::Yid,
        whatlang::Lang::Pol => Language::Pol,
        whatlang::Lang::Amh => Language::Amh,
        whatlang::Lang::Jav => Language::Jav,
        whatlang::Lang::Kor => Language::Kor,
        whatlang::Lang::Nob => Language::Nob,
        whatlang::Lang::Dan => Language::Dan,
        whatlang::Lang::Swe => Language::Swe,
        whatlang::Lang::Fin => Language::Fin,
        whatlang::Lang::Tur => Language::Tur,
        whatlang::Lang::Nld => Language::Nld,
        whatlang::Lang::Hun => Language::Hun,
        whatlang::Lang::Ces => Language::Ces,
        whatlang::Lang::Ell => Language::Ell,
        whatlang::Lang::Bul => Language::Bul,
        whatlang::Lang::Bel => Language::Bel,
        whatlang::Lang::Mar => Language::Mar,
        whatlang::Lang::Kan => Language::Kan,
        whatlang::Lang::Ron => Language::Ron,
        whatlang::Lang::Slv => Language::Slv,
        whatlang::Lang::Hrv => Language::Hrv,
        whatlang::Lang::Srp => Language::Srp,
        whatlang::Lang::Mkd => Language::Mkd,
        whatlang::Lang::Lit => Language::Lit,
        whatlang::Lang::Lav => Language::Lav,
        whatlang::Lang::Est => Language::Est,
        whatlang::Lang::Tam => Language::Tam,
        whatlang::Lang::Vie => Language::Vie,
        whatlang::Lang::Urd => Language::Urd,
        whatlang::Lang::Tha => Language::Tha,
        whatlang::Lang::Guj => Language::Guj,
        whatlang::Lang::Uzb => Language::Uzb,
        whatlang::Lang::Pan => Language::Pan,
        whatlang::Lang::Aze => Language::Aze,
        whatlang::Lang::Ind => Language::Ind,
        whatlang::Lang::Tel => Language::Tel,
        whatlang::Lang::Pes => Language::Pes,
        whatlang::Lang::Mal => Language::Mal,
        whatlang::Lang::Ori => Language::Ori,
        whatlang::Lang::Mya => Language::Mya,
        whatlang::Lang::Nep => Language::Nep,
        whatlang::Lang::Sin => Language::Sin,
        whatlang::Lang::Khm => Language::Khm,
        whatlang::Lang::Tuk => Language::Tuk,
        whatlang::Lang::Aka => Language::Aka,
        whatlang::Lang::Zul => Language::Zul,
        whatlang::Lang::Sna => Language::Sna,
        whatlang::Lang::Afr => Language::Afr,
        whatlang::Lang::Lat => Language::Lat,
        whatlang::Lang::Slk => Language::Slk,
        whatlang::Lang::Cat => Language::Cat,
        whatlang::Lang::Tgl => Language::Tgl,
        whatlang::Lang::Hye => Language::Hye,
    }
}

#[cfg(feature = "whichlang")]
pub fn whichlang_to_isolang(lang: whichlang::Lang) -> Language {
    match lang {
        whichlang::Lang::Ara => Language::Ara,
        whichlang::Lang::Cmn => Language::Cmn,
        whichlang::Lang::Deu => Language::Deu,
        whichlang::Lang::Eng => Language::Eng,
        whichlang::Lang::Fra => Language::Fra,
        whichlang::Lang::Hin => Language::Hin,
        whichlang::Lang::Ita => Language::Ita,
        whichlang::Lang::Jpn => Language::Jpn,
        whichlang::Lang::Kor => Language::Kor,
        whichlang::Lang::Nld => Language::Nld,
        whichlang::Lang::Por => Language::Por,
        whichlang::Lang::Rus => Language::Rus,
        whichlang::Lang::Spa => Language::Spa,
        whichlang::Lang::Swe => Language::Swe,
        whichlang::Lang::Tur => Language::Tur,
        whichlang::Lang::Vie => Language::Vie,
    }
}
