package fep:mrf@1.0.0;

interface types {
    /// The direction the activity is going
    enum direction {
        /// The activity is being received
        incoming,

        /// The activity is being sent out
        outgoing,
    }

    /// Error types
    variant error {
        /// Reject the activity
        reject,

        /// An error occurred but the processing can continue
        error-continue(string),

        /// An error occurred and the processing should not continue
        error-reject(string),
    }
}

world mrf {
    use types.{direction, error};

    import wasi:logging/logging;

    /// Transform an ActivityPub activity
    export transform: func(configuration: string, direction: direction, activity: string) -> result<string, error>;
}
