package mrf:wasm@1.0.0;

world mrf {
    use types.{direction, error};

    /// Transform an ActivityPub activity
    export transform: func(direction: direction, activity: string) -> result<string, error>;
}
