FROM rust:1-alpine as base
RUN rustup default nightly
RUN apk add --no-cache musl-dev make protobuf-dev
RUN cargo install cargo-chef
WORKDIR app

FROM base as planner 
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM base AS build
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json
COPY . .
RUN cargo build --bin kitsune-search-server

FROM alpine:latest
WORKDIR app
COPY --from=build /app/target/debug/kitsune-search-server .
ENTRYPOINT ["./kitsune-search-server"]