FROM rust:1-alpine AS base
RUN apk add --no-cache musl-dev make protobuf-dev
RUN cargo install cargo-chef
WORKDIR app

FROM base AS planner 
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM base AS build
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json
COPY . .
RUN cargo build --bin kitsune

FROM base AS frontend
COPY kitsune-fe .
WORKDIR kitsune-fe
RUN pnpm i && pnpm run build

FROM alpine:latest
WORKDIR app
COPY --from=build /app/target/debug/kitsune .
COPY --from=build /app/public public
COPY --from=frontend /app kitsune-fe
ENTRYPOINT ["./kitsune"]
